csv<-read.csv('household_power_consumption.txt', sep = ';', na.strings='?')
csv<-csv[csv$Date == '1/2/2007' | csv$Date == '2/2/2007',]
csv_clean<-csv[,2:9]
csv_clean[,1]<-as.POSIXct(strptime(paste(csv[,1],csv[,2]), format='%d/%m/%Y %H:%M:%S'))
rm(csv)
par(mfrow = c(2,2), mar = c(4,4,4,4))
plot(csv_clean$Time, csv_clean$Global_active_power, type = 'l', xlab = '', ylab = 'Global Active Power')
plot(csv_clean$Time, csv_clean$Voltage, type = 'l', xlab = 'datetime', ylab = 'Voltage')
plot(csv_clean$Time, csv_clean$Sub_metering_1, type = 'l', xlab = '', ylab = 'Energy sub metering', col = 'Black')
lines(csv_clean$Time, csv_clean$Sub_metering_2, type = 'l', xlab = '', ylab = 'Energy sub metering', col = 'Red')
lines(csv_clean$Time, csv_clean$Sub_metering_3, type = 'l', xlab = '', ylab = 'Energy sub metering', col = 'Blue')
legend('topright', c('Sub_metering_1','Sub_metering_2', 'Sub_metering_3'), col=c('Black', 'Red', 'Blue'),  lty=1, cex = 0.5, bty='n')
plot(csv_clean$Time, csv_clean$Global_reactive_power, type = 'l', xlab = 'datetime', ylab = 'Global_reactive_power')
dev.copy(png, file = "plot4.png")
dev.off()